---
title: "Example Run (Real Data)"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example Run (Real Data)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bascule)
```


# prepare input data
```{r eval=FALSE}
# loading the pybasilica python package
py = reticulate::import_from_path(module="pybasilica", path="/u/azads/packages/pybasilica")

# set up the data directory (all data files must reside inside this directory)
data_path = "/u/azads/signatures/dataset/"

# set up the tumor type
organ_type <- "Lung"

# Generate organ specific catalogues - include sigs found common in serena's paper
# determining the present signatures in each tumor type based on finding from Degasperi study
sbs_cat = c(paste0("SBS", c(2, 4, 1, 5, 3, 8, 13, 17, 18, 31, 92)))
dbs_cat = c(paste0("DBS", c(2, 5, 13, 20)))

catalogue_sbs = intersect(rownames(COSMIC_sbs_filt), sbs_cat)
catalogue_dbs = intersect(rownames(COSMIC_dbs), dbs_cat)

# Generate organ specific counts matrices
input_sbs = readRDS("counts_sbs.Rds") %>%
  dplyr::filter(organ==organ_type) %>%
  dplyr::select(-organ, -cohort)
input_dbs = readRDS("counts_dbs.Rds") %>%
  dplyr::filter(organ==organ_type) %>%
  dplyr::select(-organ, -cohort)

input_sbs = input_sbs[rowSums(input_sbs) > 0, ]
input_dbs = input_dbs[rowSums(input_dbs) > 0, ]
sample_ids = intersect(rownames(input_sbs), rownames(input_dbs))

counts = list("SBS"=input_sbs[sample_ids, colnames(COSMIC_sbs_filt)],
              "DBS"=input_dbs[sample_ids, colnames(COSMIC_dbs)])

reference_cat = list("SBS"=COSMIC_sbs_filt[catalogue_sbs,],
                     "DBS"=COSMIC_dbs[catalogue_dbs,])
```

# Fitting the Model
```{r eval=FALSE}

x = fit(
  counts=counts,
  k_list=0:25,
  cluster=15,
  reference_cat=reference_cat,
  n_steps=3000, lr=0.005,
  seed_list=c(19,255,18321,331),
  hyperparameters=list("penalty_scale"=0, "alpha_conc"=alpha_conc),
  store_fits=TRUE,
  py=py, CUDA=TRUE, autoguide=TRUE
)

```


# Refine the signatures
Here, we are trying to eliminate all de novo signatures that are explainable with linear combination of the other signatures.

```{r eval=FALSE}
x_refined <- basilica:::refine_denovo_signatures(x)
```

# Re-Clustering
we perform the clustering step, using the new set of signatures.

```{r eval=FALSE}
x_refined_cls <- bascule:::fit_clustering(
  x_refined,
  cluster = 15,
  seed_list=c(19,255,18321,331),
  hyperparameters=list("penalty_scale"=0, "alpha_conc"=alpha_conc),
  store_fits=TRUE,
  py=py, CUDA=TRUE, autoguide=TRUE
)
```


# Visualization

```{r eval=FALSE}

# plot the fixed and denovo signatures
bascule:::plot_signatures(x)

# plot the exposure matrix
bascule:::plot_exposures(x)

# plot the centroids
plot_centroids(x)

```


